### ISSUE TITLE
Issue saving file when provided path

### ISSUE THREAD

**Issue by klmcadams** [ansys/pymechanical#307]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Issue saving mechdat file given path:

CRITICAL - - logging - handle_exception - Uncaught exception
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "C:\...\ansys\mechanical\core\embedding\app.py", line 107, in save self.DataModel.Project.Save(path)

System.Exception: Failed to save project: System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
    at Ansys.Common.Interop.AnsysWB.IWBAppletList.get_Applet(String bsName)
    at Ansys.ACT.Mechanical.Standalone.AddtoRecentFiles(String filePath)
    at Ansys.ACT.Mechanical.Standalone.SaveAs(String filePath)
    at Ansys.ACT.Automation.Mechanical.Project.SaveAs(String filePath)
    at Ansys.ACT.Automation.Mechanical.Project.LogAndThrow(String filePath)
    at Ansys.ACT.Automation.Mechanical.Project.SaveAs(String filePath)
    at Ansys.ACT.Automation.Mechanical.Project.Save(String filePath)

### 📝 Steps to reproduce

import os 
from ansys.mechanical.core import App, global_variables

app = App(version=241)
globals().update(global_variables(app))
print(app)

path = r"C:\...\generic_241.mechdat"
app.save(path)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
N/A
```

**Comment by klmcadams** [comment]
This issue is fixed
